import '@/styles/global.css'
import Header from '@/components/header'
import PromptInput from '@/components/promptInput'
import ClientProvider from '@/components/clientProvider'

export const metadata = {
  title: 'G-hack AI Gallery',
  description: 'Generated by ghack9293',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>
          <Header/>
          <PromptInput/>
          {children}
        </ClientProvider>
        </body>
    </html>
  )
}
